export enum ActionsEnum {
    IDLE="IDLE",
    SUCCESS="SUCCESS",
    ERROR="ERROR",
    LOADING="LOADING"
}

export enum StatusOfOrder {
    CREATED="CREATED",
    PAYMENT="PAYMENT",
    READYFORDELIVERY="READYFORDELIVERY",
    DELIVERY="DELIVERY",
    SUCCESS = "SUCCESS",
    CANCELED = "CANCELED",
    ERROR="ERROR",
}